import type { Metadata } from "next";
import { Lemon, Oi, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const lemon = Lemon({
  weight: '400', 
  subsets: ['latin'], 
  variable: '--font-lemon', 
});

const oi = Oi({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-oi',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lemon.variable} ${oi.variable} antialiased bg-black text-white`}
      >
        {children}
      </body>
    </html>
  );
}
